"use client";

import { useState, useEffect, useRef } from "react";
import { X, Loader2, Shield, Copy, Calendar } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import { motion } from "framer-motion";
import { useGenerateProof, useSubmitProof, BirthDateInput } from "@/hooks/useZKProof";
import type { Credential } from "@/types";
import toast from "react-hot-toast";

type Props = {
  credential: Credential;
  onClose: () => void;
  onProofGenerated?: (proofLink: string) => void;
  autoGenerate?: boolean;
};

type ProofType = "age_above_18" | "age_above_21" | "credential_ownership" | "citizenship" | "degree";

const getProofOptions = (credentialType: string) => {
  if (credentialType === "Citizenship") {
    return [{ id: "citizenship" as ProofType, label: "Prove Citizenship", desc: "Confirm you are a valid citizen" }];
  }
  if (credentialType === "Degree") {
    return [{ id: "degree" as ProofType, label: "Prove Degree", desc: "Confirm your university degree" }];
  }
  if (credentialType === "AgeProof") {
    return [{ id: "age_above_18" as ProofType, label: "Age ≥ 18", desc: "Prove you're an adult" }];
  }
  return [{ id: "credential_ownership" as ProofType, label: "Credential Ownership", desc: "Prove you hold this VC" }];
};

export function ShareProofModal({ credential, onClose, onProofGenerated, autoGenerate = false }: Props) {
  const options = getProofOptions(credential.type);
  const [proofType, setProofType] = useState<ProofType>(options[0].id);
  const [proofLink, setProofLink] = useState<string | null>(null);
  const [qrContent, setQrContent] = useState<string | null>(null);
  const [birthDate, setBirthDate] = useState<BirthDateInput | null>(
    autoGenerate ? { birthYear: 2000, birthMonth: 1, birthDay: 1 } : null
  );
  const { generateProof, isGenerating } = useGenerateProof();
  const { submitAgeProof, submitCredentialProof, isPending } = useSubmitProof();
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
  }, [autoGenerate]);

  async function handleGenerate() {
    const effectiveProofType = options[0].id;
    const effectiveBirthDate = birthDate || { birthYear: 2000, birthMonth: 1, birthDay: 1 };

    if (effectiveProofType !== "credential_ownership" && !effectiveBirthDate && !autoGenerate) {
      toast.error("Please enter your birth date");
      return;
    }

    try {
      const actualProofType = (effectiveProofType === "citizenship" || effectiveProofType === "degree")
        ? "credential_ownership"
        : effectiveProofType as "age_above_18" | "age_above_21" | "credential_ownership";

      const result = await generateProof(credential, actualProofType, effectiveBirthDate);

      const toastId = toast.loading("Submitting proof on-chain...");
      try {
        if (actualProofType === "age_above_18" || actualProofType === "age_above_21") {
          await submitAgeProof(result.proof, result.publicInputs as `0x${string}`[]);
        } else {
          await submitCredentialProof(result.proof, result.publicInputs as `0x${string}`[]);
        }
        toast.dismiss(toastId);
        toast.success("Proof verified on-chain!");

        // Custom verification display data
        let claimType = "Credential Ownership";
        let verifiedMsg = "VERIFIED - Valid Credential";

        if (credential.type === "Citizenship") {
          claimType = "Citizenship Proof";
          verifiedMsg = "VERIFIED - Valid Indian Citizen";
        } else if (credential.type === "Degree") {
          claimType = "University Degree";
          verifiedMsg = "VERIFIED - Valid University Degree";
        } else if (credential.type === "AgeProof") {
          claimType = "Age Proof";
          verifiedMsg = "VERIFIED - Over 18 Years Old";
        }

        const proofHex = typeof result.proof === 'string' ? result.proof : Buffer.from(result.proof).toString("hex");

        const jsonOutput = JSON.stringify({
          proof: `0x${proofHex}`,
          nullifier: result.nullifier,
          publicClaimType: claimType,
          status: verifiedMsg
        }, null, 2);

        setQrContent(jsonOutput);

        const url = new URL(result.proofLink);
        url.searchParams.set("claim", claimType);
        url.searchParams.set("msg", verifiedMsg);
        url.searchParams.set("proof", `0x${proofHex}`);
        const finalLink = url.toString();

        setProofLink(finalLink);
        if (onProofGenerated) {
          onProofGenerated(finalLink);
        }
      } catch (submitErr) {
        toast.dismiss(toastId);
        throw submitErr;
      }
    } catch (err) {
      console.error("Proof generation error:", err);
      toast.error("Failed to generate or submit proof");
    }
  }

  function copyLink() {
    if (proofLink) {
      navigator.clipboard.writeText(proofLink);
      toast.success("Link copied!");
    }
  }

  function handleBirthDateChange(field: "birthYear" | "birthMonth" | "birthDay", value: string) {
    const num = parseInt(value, 10);
    if (isNaN(num)) return;

    setBirthDate(prev => ({
      birthYear: field === "birthYear" ? num : (prev?.birthYear ?? 2000),
      birthMonth: field === "birthMonth" ? num : (prev?.birthMonth ?? 1),
      birthDay: field === "birthDay" ? num : (prev?.birthDay ?? 1),
    }));
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm px-4">
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        className="w-full max-w-md glow-card rounded-2xl bg-surface-900 p-6"
      >
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-brand-500/20 border border-brand-500/30 flex items-center justify-center">
              <Shield className="w-4 h-4 text-brand-400" />
            </div>
            <div>
              <div className="font-semibold text-slate-200 text-sm">Generate ZK Proof</div>
              <div className="text-xs text-slate-500">{credential.type}</div>
            </div>
          </div>
          <button onClick={onClose} className="text-slate-500 hover:text-slate-300 transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        {!proofLink ? (
          <div className="py-12 flex flex-col items-center justify-center space-y-4">
            <Loader2 className="w-8 h-8 text-brand-500 animate-spin" />
            <p className="text-sm text-slate-400 font-medium">
              {isGenerating ? "Generating ZK Proof..." : "Preparing..."}
            </p>
          </div>
        ) : (
          <div className="text-center space-y-4">
            {/* QR code */}
            <div className="flex justify-center p-4 bg-white rounded-xl">
              <QRCodeSVG value={qrContent || proofLink} size={180} />
            </div>

            <p className="text-xs text-slate-400 font-medium">
              Scan this QR or share the link below.
            </p>

            {/* Copy link */}
            <div className="flex items-center gap-2 p-3 rounded-xl bg-surface-950 border border-slate-800">
              <code className="flex-1 text-[10px] text-brand-300 font-mono truncate">{proofLink}</code>
              <button onClick={copyLink} className="text-slate-400 hover:text-slate-200 transition-colors">
                <Copy className="w-4 h-4" />
              </button>
            </div>

            <button
              onClick={() => {
                hasAutoGenerated.current = false;
                setProofLink(null);
                handleGenerate();
              }}
              className="text-xs text-slate-500 hover:text-slate-300 transition-colors font-medium"
            >
              Generate another proof
            </button>
          </div>
        )}
      </motion.div>
    </div>
  );
}
